package:
  name: lmfit
  version: 0.9.3

build:
  number: 0
  #  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

  # Note that this will override the default build string with the Python
  # and NumPy versions
  #  string: {{ environ.get('GIT_BUILD_STR', '') }}

source:
  git_url: https://github.com/lmfit/lmfit-py.git
  git_tag: 0.9.3

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy

  run:
    - python
    - numpy
    - scipy

test:
  imports:
    - lmfit
    - lmfit.ui
    - lmfit.uncertainties

about:
  home: http://lmfit.github.io/lmfit-py/
  license: MIT
  summary: Least-Squares Minimization with Bounds and Constraints
